name: hik_flutter
description: This is a Flutter plugin for HikVision (HCNetSDK).
version: 1.0.0
homepage: https://github.com/thongdn-it/hik_flutter

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: thongdn.dev.hik_flutter
        pluginClass: HikFlutterPlugin
      ios:
        pluginClass: HikFlutterPlugin